# Generated by Django 5.2.6 on 2025-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='auto_send',
            field=models.BooleanField(default=True, help_text='Send notification immediately after saving'),
        ),
    ]
